### ISSUE TITLE
Failed to boot gateway_config

### ISSUE THREAD

**Issue by Wheaties466** [helium/gateway-config#65] opened 2020-09-30 15:07 UTC
I know this wasn't built for the DIYs but I would like to have an option for configuring the DIY hotspots over bluetooth.

` sudo ./rebar3 shell
===> Verifying dependencies...
===> Compiling gateway_config
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Eshell V10.2.4  (abort with ^G)
1> ===> The rebar3 shell is a development tool; to deploy applications in production, consider using releases (http://www.rebar3.org/docs/releases)
===> Booted syntax_tools
===> Booted compiler
===> Booted goldrush
===> Booted lager
===> Booted ebus
===> Failed to boot gateway_config for reason {{shutdown,
                                                           {failed_to_start_child,
                                                            gateway_gatt_application,
                                                            {shutdown,
                                                             {failed_to_start_child,
                                                              application,
                                                              {error,
                                                               no_adapter}}}}},
                                                          {gateway_config_app,
                                                           start,
                                                           [normal,[]]}}
`

After compiling I am getting this error when running the dev shell. Any help would be appreciated.

**Comment by fvasquez** [comment] 2020-09-30 16:14
You're right about `gateway_config` not having been built for DIY hotspots. I have a RAK LoRa gateway sitting on my desk that I would like to dedicate to mining HNT so I may be able to help you and myself. What hardware are you using and what OS are you running?

**Comment by Wheaties466** [comment] 2020-09-30 16:17
Its a RAK 7243

raspberry pi 3, raspberian lite.

My goal is to be able to configure wifi over bluetooth.

**Comment by philltran** [comment] 2020-09-30 19:22
I am using a Raspberry Pi 4b and a Rak2287 on Raspberian lite 64bit. I am willing to test or help however I can.

**Comment by Wheaties466** [comment] 2020-10-07 18:34
Let me run through some steps I did to get the bluetooth advertising working.

```
sudo apt install bluetooth pi-bluetooth libdbus-1-dev cmake -y
sudo reboot

sudo bluetoothctl
list   #this needs to show an adapter
exit

git clone https://github.com/helium/gateway-config.git
cd gateway-config
make && make release

sudo _build/prod/rel/gateway_config/bin/gateway_config start
_build/prod/rel/gateway_config/bin/gateway_config advertise on
```

This allows me to connect to the pi hotspot with the hotspot utility app in the iphone app store. I get limited information, but its better than nothing right now. I'm guessing this is just a difference in OSs and where the information is kept.

**Comment by mjohngreene** [comment] 2020-10-07 20:48
Cross posting from Discord:

I did a little digging a few weeks ago without much luck.  I think it is going to take some extra effort along the lines of https://scribles.net/creating-altbeacon-with-raspberry-pi-using-bluez-example-code-updated/ to an RPi to advertise and allow other devices to connect.

I get a little lost in step 2-3 with all of the hex codes.

**Comment by fvasquez** [comment] 2020-10-15 22:26
BlueZ needs to be configured so that a DIY hotspot advertises itself as something like "Helium Hotspot DC85". Otherwise the Helium mobile app cannot scan or pair with it. The "DC85" is the last 4 digits of the hotspot's Wi-Fi MAC address. You can use a BLE scanner app like nRF Connect to dissect the advertisement from a real hotspot. I also recall needing an XML configuration file so that `gateway_config` could talk to `connmand` and `miner` over D-Bus. This service start script and configuration file should probably be added to the repo.

**Comment by mjohngreene** [comment] 2020-10-18 17:16
@fvasquez I am not familiar with onboarding a hotspot.  I have been waiting for DIYs to be allowed "on chain" and most all of the work I have done re Helium gateways is in preparation for that.

On that note, do you know if the roadmap contemplates necessitating BLE and/or the Helium app to onboard DIYs?  I got an Alpha code to onboard a DIY which did not require use of a phone/BLE app.  I was thinking of ways to use a similar process to onboard DIYs and then add their WiFi credentials via BLE once at a host's site.  Are you aware of reasons that might not work/be a good idea?

**Comment by Wheaties466** [comment] 2020-10-19 13:11
> @fvasquez I am not familiar with onboarding a hotspot. I have been waiting for DIYs to be allowed "on chain" and most all of the work I have done re Helium gateways is in preparation for that. I have a few RPi 0 gateways running Raspbian Lite and pointing to AWS miners teed up and ready to go.
> 
> I have been contemplating how to onboard these DIYs at a host's location. To that end, do you know if the roadmap contemplates necessitating BLE and/or the Helium app to onboard DIYs? I got an Alpha code to onboard a DIY which did not require use of a phone/BLE app. I was thinking of ways to use a similar process to get the GW configured in advance to the greatest extent possible and then adding hosts' WiFi credentials via BLE. Unfortunately, though, I don't fully grok the issues around security, location, etc. vis-a-vis blockchain. Are you aware of reasons/concerns that setting up WiFi over BLE might be problematic?

If you were able to get an onboarding code the DIYs can absolutely join the blockchain.


I have a script that assists in joining DIYs to the block chain via ssh access.

https://github.com/Wheaties466/helium_miner_scripts/blob/dev/add_gateway_to_blockchain.sh

I've been playing around with getting this to work and setting up a way to change wifi credentials.

https://github.com/jasbur/RaspiWiFi

I suppose it would be within the realm of possibility to write a gui and run a similar script to onboard the miner. Even though it is not recommended to have the helium-miner software on the pi itself. ( it takes like 45 min to run some of the commands)

**Comment by mjohngreene** [comment] 2020-10-19 16:57
Thanks, @Wheaties466 .  To clarify: I successfully onboarded my DIY (a headless RAK RPi 0) a month or so ago to point to a miner running on AWS.  I have also used an access point on my Android phone to update wpa_supplicant.conf once connected to wifi.  So, no issues with any of that.  I am now figuring out how to set everything up to the greatest extent possible before going to a host's site to do the install.  

I could do all of the onboarding to the chain stuff and even customize each gateway with the host's wifi creds using wpa_supplicant.conf ahead of time.  That is somewhat less than optimal, though, as I’d have to know both wifi creds and GPS location ahead of time and then track/manage the pre-configured/credentialed gateways until deployed.  It would be much preferable, IMO, to standardize my GW build and then do just the wifi/onboarding once on site.

I have connected my Android to a gateway over Bluetooth.  So, the only piece I'm really missing now to accomplish all of this is some way to interface with the GW from the phone to enter the host's wifi creds.  If I could figure that out, I could then do all of the chain onboarding via SSH on site.

Note that none of the above uses the Helium app.  I am still unclear, however, as to whether the Helium app is necessary for some sort of security/blockchain validation function associated with onboarding.

**Comment by fvasquez** [comment] 2020-10-20 01:26
> @fvasquez I am not familiar with onboarding a hotspot. I have been waiting for DIYs to be allowed "on chain" and most all of the work I have done re Helium gateways is in preparation for that. I have a few RPi 0 gateways running Raspbian Lite and pointing to AWS miners teed up and ready to go.

@mjohngreene onboarding a consumer Helium Hotspot is typically a 3-step process.

1. Connecting the Helium Hotspot to a WiFi network.
2. Adding the Helium Hotspot to the blockchain.
3. Asserting the location of the Helium Hotspot.

If your RPi 0 gateways are just running the LoRa `packet_forwarder` without a `miner` on board then you only need to execute step 1 on each gateway. Steps 2 and 3 (`add_gateway` and `assert_location`) are blockchain transactions that involve a `miner`. The Helium mobile app submits both transactions via a web API on behalf of a `miner`. I imagine the wallet CLI is being used to onboard miners for the purposes of the DIY alpha program. I don't know since I was not involved in the DIY alpha. I bought my Hotspot from Helium.

As you pointed out, you don't need BLE or the Helium mobile app to connect a device running Raspbian Lite to a WiFi network.  I realize that onboarding a gateway is harder without the Helium mobile app but building and starting `gateway_config` along with D-Bus, BlueZ, and `connmand` on your gateways is probably not worth the effort.  I'm also skeptical that steps 2 and 3 will even work from the Helium mobile app without a `miner` running on the same target gateway.

A Helium engineer is working on an alternative mobile app meant to address some of your bulk onboarding concerns. It was designed for patrons with several Helium Hotspots deployed in various locations.

https://github.com/kent-williams/hotspot-utility

I can tell you that a Helium Hotspot can only connect to a WiFi network that appears in a WiFi scan. Uploading WiFi credentials to a Helium Hotspot for connecting later is not supported because I never implemented that feature in `gateway_config`.

**Comment by Wheaties466** [comment] 2020-10-20 13:11
> > @fvasquez I am not familiar with onboarding a hotspot. I have been waiting for DIYs to be allowed "on chain" and most all of the work I have done re Helium gateways is in preparation for that. I have a few RPi 0 gateways running Raspbian Lite and pointing to AWS miners teed up and ready to go.
> 
> @mjohngreene onboarding a consumer Helium Hotspot is typically a 3-step process.
> 
> 1. Connecting the Helium Hotspot to a WiFi network.
> 2. Adding the Helium Hotspot to the blockchain.
> 3. Asserting the location of the Helium Hotspot.
> 
> If your RPi 0 gateways are just running the LoRa `packet_forwarder` without a `miner` on board then you only need to execute step 1 on each gateway. Steps 2 and 3 (`add_gateway` and `assert_location`) are blockchain transactions that involve a `miner`. The Helium mobile app submits both transactions via a web API on behalf of a `miner`. I imagine the wallet CLI is being used to onboard miners for the purposes of the DIY alpha program. I don't know since I was not involved in the DIY alpha. I bought my Hotspot from Helium.
> 
> As you pointed out, you don't need BLE or the Helium mobile app to connect a device running Raspbian Lite to a WiFi network. I realize that onboarding a gateway is harder without the Helium mobile app but building and starting `gateway_config` along with D-Bus, BlueZ, and `connmand` on your gateways is probably not worth the effort. I'm also skeptical that steps 2 and 3 will even work from the Helium mobile app without a `miner` running on the same target gateway.
> 
> A Helium engineer is working on an alternative mobile app meant to address some of your bulk onboarding concerns. It was designed for patrons with several Helium Hotspots deployed in various locations.
> 
> https://github.com/kent-williams/hotspot-utility
> 
> I can tell you that a Helium Hotspot can only connect to a WiFi network that appears in a WiFi scan. Uploading WiFi credentials to a Helium Hotspot for connecting later is not supported because I never implemented that feature in `gateway_config`.

I have downloaded and used the app mentioned.

Also you are correct that it wouldn't work without the miner software running. Right now I am in the process of getting connmand to work with gateway config. I seem to have everything else working as I would expect. I suspect I may be dealing with a permission issue of some sort. 

My personal goal was not to do #2 and #3 you have listed as it would take a very long time for the helium-wallet to run the  commands associated with adding a hotspot to the blockchain(~45 min) and I have been told time and time again that running the wallet software wasn't meant to be run locally. 

I am really just looking to have the ability to connect to the miner and change the wifi network and grab diagnostics. Everything else that is accomplished is gravy.

**Comment by mjohngreene** [comment] 2020-10-20 13:19
@fvasquez Thanks for the additional feedback.  I am only really trying to figure out how to do the first step on your list.  I realize now that this is not the correct repo to be using to figure out how to do that.  The exchange has been helpful in clarifying my thoughts, though, so that is appreciated.

**Comment by Wheaties466** [comment] 2020-10-20 13:31
@mjohngreene I think I disagree. In my opinion I think this would be the correct repo to do just that.

**Comment by fvasquez** [comment] 2020-10-20 17:02
> I am only really trying to figure out how to do the first step on your list. I realize now that this is not the correct repo to be using to figure out how to do that.

I consider sending down the WiFi credentials so that a Helium Hotspot can connect to the internet to be the primary feature of `gateway_config`. @madninja and I originally developed `gateway_config` strictly with consumers in mind. There were no visions of patrons or DIY hotspots at the time. You are not the first person to ask for the ability to connect to a WiFi network that does not appear in a WiFi scan (upload WiFi credentials for later use). I will open an issue against this repo requesting that feature.

**Comment by philltran** [comment] 2020-10-21 03:37
@Wheaties466 

Can you try running a bash script like this on boot?

```
#!/bin/sh
/bin/sv check /etc/sv/bluetoothd >/dev/null || exit
/bin/sv check /etc/sv/connmand >/dev/null   || exit
/usr/sbin/gw_config_gpios
/usr/bin/connmanctl enable bluetooth
# Advertise on channels 37, 38 and 39
echo 7 > /sys/kernel/debug/bluetooth/hci0/adv_channel_map
# Send a beacon every 152.5 ms
echo 153 > /sys/kernel/debug/bluetooth/hci0/adv_min_interval
echo 153 > /sys/kernel/debug/bluetooth/hci0/adv_max_interval
echo -e "pairable off\nquit" | /usr/bin/bluetoothctl
/sbin/ifconfig lo up
export DBUS_SESSION_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
export RUNNER_LOG_DIR="/var/data/log/gateway_config"
export ERL_CRASH_DUMP="/var/data/log/gateway_config"
export ERL_EPMD_ADDRESS="127.0.0.1"
export ERL_FULLSWEEP_AFTER=0 ## don't care about performance, just don't eat RAM
## don't have a button, just enable pairing on bootup
(/bin/sleep 10 && /opt/gateway_config/bin/gateway_config advertise on) &
exec /opt/gateway_config/bin/gateway_config foreground
```

**Comment by fvasquez** [comment] 2020-10-21 05:26
Smartphones are very particular about Bluetooth advertising channels and beacon intervals. If I remember correctly the Helium Hotspot uses the settings recommended by Apple's [Accessory Design Guidelines](https://developer.apple.com/accessories/Accessory-Design-Guidelines.pdf).

**Comment by Wheaties466** [comment] 2020-10-21 16:24
> @Wheaties466
> 
> Can you try running a bash script like this on boot?
> 
> ```
> #!/bin/sh
> /bin/sv check /etc/sv/bluetoothd >/dev/null || exit
> /bin/sv check /etc/sv/connmand >/dev/null   || exit
> /usr/sbin/gw_config_gpios
> /usr/bin/connmanctl enable bluetooth
> # Advertise on channels 37, 38 and 39
> echo 7 > /sys/kernel/debug/bluetooth/hci0/adv_channel_map
> # Send a beacon every 152.5 ms
> echo 153 > /sys/kernel/debug/bluetooth/hci0/adv_min_interval
> echo 153 > /sys/kernel/debug/bluetooth/hci0/adv_max_interval
> echo -e "pairable off\nquit" | /usr/bin/bluetoothctl
> /sbin/ifconfig lo up
> export DBUS_SESSION_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
> export RUNNER_LOG_DIR="/var/data/log/gateway_config"
> export ERL_CRASH_DUMP="/var/data/log/gateway_config"
> export ERL_EPMD_ADDRESS="127.0.0.1"
> export ERL_FULLSWEEP_AFTER=0 ## don't care about performance, just don't eat RAM
> ## don't have a button, just enable pairing on bootup
> (/bin/sleep 10 && /opt/gateway_config/bin/gateway_config advertise on) &
> exec /opt/gateway_config/bin/gateway_config foreground
> ```

Troubleshooting a wireless issue with my pi right now but I can certainly do this.

I know this is doing more than just activating bluetooth. But I can get bluetooth started and paired just fine. Its the other compontents of gateway_config that are alluding me.

**Comment by philltran** [comment] 2020-10-21 16:35
This was the code from the black spot

**Comment by fvasquez** [comment] 2020-10-23 07:11
@mjohngreene there is [WiFi Connect](https://github.com/balena-io/wifi-connect) from balena if all you need is WiFi. It's supposed to work with Raspbian and balenaOS.

**Comment by madninja** [comment] 2020-12-30 13:39
I'm going to close this for now for lack of progress. Re-open with more info if you made progress with your setup?

**Closed by madninja** 2020-12-30 13:39 UTC
